// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLYKJAN_tAaXT4ROSRr5pEX4CNPBEN3M',
    appId: '1:707447825874:web:545c858e1fb832308a540b',
    messagingSenderId: '707447825874',
    projectId: 'telemed-vincent-app',
    authDomain: 'telemed-vincent-app.firebaseapp.com',
    storageBucket: 'telemed-vincent-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_q5fJhB2yAovspsXYh0bd_KEDP0U3Kw',
    appId: '1:707447825874:android:36f3f4ea95dca9b88a540b',
    messagingSenderId: '707447825874',
    projectId: 'telemed-vincent-app',
    storageBucket: 'telemed-vincent-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl2_FcibiK70XN8xHLBduveme9ckWi9wY',
    appId: '1:707447825874:ios:f53606f3817211638a540b',
    messagingSenderId: '707447825874',
    projectId: 'telemed-vincent-app',
    storageBucket: 'telemed-vincent-app.firebasestorage.app',
    iosBundleId: 'com.example.telemedStarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl2_FcibiK70XN8xHLBduveme9ckWi9wY',
    appId: '1:707447825874:ios:f53606f3817211638a540b',
    messagingSenderId: '707447825874',
    projectId: 'telemed-vincent-app',
    storageBucket: 'telemed-vincent-app.firebasestorage.app',
    iosBundleId: 'com.example.telemedStarter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxLYKJAN_tAaXT4ROSRr5pEX4CNPBEN3M',
    appId: '1:707447825874:web:27bbffb5a1339a6b8a540b',
    messagingSenderId: '707447825874',
    projectId: 'telemed-vincent-app',
    authDomain: 'telemed-vincent-app.firebaseapp.com',
    storageBucket: 'telemed-vincent-app.firebasestorage.app',
  );
}
